name: DAILY SYSTEM WARNING
on:
  workflow_dispatch:
  schedule:
  - cron:  '0 23 * * *'
jobs:
  main:
    name: DAILY SYSTEM WARNING
    runs-on: ubuntu-latest
    steps:
      - name: 'CHECKOUT'
        uses: actions/checkout@v3
      - name: 'SEND WARNING'
        uses: appleboy/discord-action@master
        with:
          webhook_id: "${{ secrets.DAILY_WEBHOOK_ID }}"
          webhook_token: "${{ secrets.DAILY_WEBHOOK_TOKEN }}"
          color: "#90EE90"
          args: "${{ secrets.DAILY_WARNING }}"
